// upcoming
export const UPCOMING_MOVIES_REQUEST = 'UPCOMING_MOVIES_REQUEST';
export const UPCOMING_MOVIES_SUCCESS = 'UPCOMING_MOVIES_SUCCESS';
export const UPCOMING_MOVIE_DETAIL_REQUEST = 'UPCOMING_MOVIE_DETAIL_REQUEST';

// now playing
export const GET_NOW_PLAYING_MOVIES_REQUEST = 'GET_NOW_PLAYING_MOVIES_REQUEST';
export const GET_NOW_PLAYING_MOVIES_SUCCESS = 'GET_NOW_PLAYING_MOVIES_SUCCESS';

// latest
export const GET_MOVIE_LATEST_REQUEST = 'GET_MOVIE_LATEST_REQUEST';

// top rated
export const GET_TOP_RATED_MOVIE_SUCCESS = 'GET_TOP_RATED_MOVIE_SUCCESS';

// similar
export const GET_SIMILAR_MOVIE_REQUEST = 'GET_SIMILAR_MOVIE_REQUEST';

// popular
export const POPULAR_MOVIES_REQUEST = 'POPULAR_MOVIES_REQUEST';
export const POPULAR_MOVIE_DETAIL_REQUEST = 'POPULAR_MOVIE_DETAIL_REQUEST';
export const POPULAR_MOVIE_DETAIL_SUCCESS = 'POPULAR_MOVIE_DETAIL_SUCCESS';

// genre
export const GET_GENRE_TYPE_LIST_REQUEST = 'GET_GENRE_TYPE_LIST_REQUEST';

// reviews
export const GET_MOVIE_DETAIL_REVIEW = 'GET_MOVIE_DETAIL_REVIEW';

// TV on_the_air
export const GET_TV_ON_THE_AIR_REQUEST = 'GET_TV_ON_THE_AIR_REQUEST';

// credits
export const GET_MOVIE_DETAIL_CREDIT_SUCCESS = 'GET_MOVIE_DETAIL_CREDIT_SUCCESS';

// videos
export const GET_MOVIE_DETAIL_VIDEO_REQUEST = 'GET_MOVIE_DETAIL_VIDEO_REQUEST';
export const GET_MOVIE_DETAIL_VIDEO_SUCCESS = 'GET_MOVIE_DETAIL_VIDEO_SUCCESS';