export const UPCOMING_MOVIES_REQUEST = 'UPCOMING_MOVIES_REQUEST';
export const UPCOMING_MOVIES_SUCCESS = 'UPCOMING_MOVIES_SUCCESS';

export const GET_NOW_PLAYING_MOVIES_REQUEST = 'GET_NOW_PLAYING_MOVIES_REQUEST';
export const GET_NOW_PLAYING_MOVIES_SUCCESS = 'GET_NOW_PLAYING_MOVIES_SUCCESS';

export const POPULAR_MOVIES_REQUEST = 'POPULAR_MOVIES_REQUEST';

export const GET_GENRE_TYPE_LIST_REQUEST = 'GET_GENRE_TYPE_LIST_REQUEST';